# Generated by Django 5.2.4 on 2026-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('бакалавриат', 'Бакалавриат'),
                            ('специалитет', 'Специалитет'),
                        ],
                        max_length=32,
                        verbose_name='Уровень подготовки',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        max_length=9, unique=True, verbose_name='Код направления'
                    ),
                ),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ('code',),
            },
        ),
    ]
