# Generated by Django 5.2.4 on 2026-05-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_academic_year_settings_semester_fk'),
        ('teams', '0002_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                (
                    'code',
                    models.CharField(
                        blank=True, default='', max_length=64, verbose_name='Код'
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='study_groups',
                        to='accounts.department',
                        verbose_name='Подразделение',
                    ),
                ),
                (
                    'direction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='study_groups',
                        to='teams.direction',
                        verbose_name='Направление подготовки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ('department', 'name'),
            },
        ),
    ]
