# Generated by Django 5.2.4 on 2026-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='course_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер курса'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='Закончили обучение'),
        ),
    ]
