# Generated by Django 5.2.4 on 2026-07-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_direction_code_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='enrollment_year',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Год набора'
            ),
        ),
    ]
