# Generated by Django 5.2.4 on 2026-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_studygroup_enrollment_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="profile",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Профиль"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="form",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Форма обучения"
            ),
        ),
    ]
