# Generated by Django 5.2.4 on 2026-08-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_user_mentor_fields"),
        ("teams", "0008_studygroup_profile_form"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__code": "mentor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_study_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Наставник",
            ),
        ),
    ]
