# Generated by Django 5.2.4 on 2026-08-25 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_mentor_fields'),
        ('showcase', '0037_projecttrack_recommended_teams_count'),
        ('teams', '0013_team_lobby_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teameventlog',
            index=models.Index(
                fields=['team_semester', 'created_at'], name='event_log_ts_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(
                fields=['user', 'status'], name='invite_user_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='teamjoinrequest',
            index=models.Index(
                fields=['user', 'status'], name='join_req_user_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='teamsemester',
            index=models.Index(
                fields=['semester', 'project_track'], name='team_sem_semester_track_idx'
            ),
        ),
    ]
