# Generated by Django 5.2.4 on 2026-08-27 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_mentor_fields'),
        ('showcase', '0038_alter_team_member_limits_default_4_7'),
        ('teams', '0014_lobby_query_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teamsemester',
            index=models.Index(
                fields=['semester', 'project_track', 'project_application'],
                name='team_sem_enroll_lookup_idx',
            ),
        ),
    ]
