# Generated by Django 5.2.4 on 2026-08-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_mentor_fields'),
        ('teams', '0015_team_sem_enroll_lookup_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroupSemester',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'mentor',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'role__code': 'mentor'},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='mentored_group_semesters',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Наставник',
                    ),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='study_group_semesters',
                        to='accounts.semester',
                        verbose_name='Семестр',
                    ),
                ),
                (
                    'study_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='semester_enrollments',
                        to='teams.studygroup',
                        verbose_name='Учебная группа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Группа в семестре',
                'verbose_name_plural': 'Группы в семестрах',
                'ordering': ('study_group', 'semester'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('study_group', 'semester'),
                        name='unique_study_group_semester',
                    )
                ],
            },
        ),
    ]
