# Generated by Django 5.2.4 on 2026-08-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_preregistration_generalize'),
        ('teams', '0018_studygroupsemester_mentors_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupsemester',
            name='mentors',
            field=models.ManyToManyField(
                blank=True,
                related_name='mentored_group_semesters',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Наставники',
            ),
        ),
        migrations.CreateModel(
            name='StudyGroupProjectTeacher',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'mentor_full_name',
                    models.CharField(max_length=255, verbose_name='ФИО наставника'),
                ),
                (
                    'external_teacher_id',
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        verbose_name='ID преподавателя (1С)',
                    ),
                ),
                (
                    'external_group_id',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=32,
                        verbose_name='ID группы (1С)',
                    ),
                ),
                (
                    'mentor_short_name',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=64,
                        verbose_name='ФИО наставника (кратко)',
                    ),
                ),
                (
                    'lesson_count',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name='Кол-во пар'
                    ),
                ),
                (
                    'import_status',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=32,
                        verbose_name='Статус импорта',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='project_teachers',
                        to='accounts.semester',
                        verbose_name='Семестр',
                    ),
                ),
                (
                    'study_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_teachers',
                        to='teams.studygroup',
                        verbose_name='Учебная группа',
                    ),
                ),
                (
                    'tutor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='project_teacher_assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Преподаватель в PD',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Преподаватель проектной деятельности группы',
                'verbose_name_plural': 'Преподаватели проектной деятельности групп',
                'ordering': ('study_group', 'semester', 'external_teacher_id'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('semester', 'study_group', 'external_teacher_id'),
                        name='unique_project_teacher_per_group_semester',
                    )
                ],
            },
        ),
    ]
