# Generated by Django 5.2.4 on 2026-09-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_team_sem_enroll_partial_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMixedTeamCreate',
            fields=[
            ],
            options={
                'verbose_name': 'Сборка смешанной команды',
                'verbose_name_plural': 'Сборка смешанной команды',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teams.team',),
        ),
    ]
