# Generated by Django 5.2.4 on 2025-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_department_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="short_name",
            field=models.CharField(
                default="-", max_length=64, verbose_name="Краткое название"
            ),
            preserve_default=False,
        ),
    ]
