# Generated by Django 5.2.4 on 2025-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
