# Generated by Django 5.2.4 on 2025-07-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Код роли",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название роли"),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
                verbose_name="Роль",
            ),
        ),
    ]
