# Generated by Django 5.2.4 on 2025-10-16 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Подана"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="submitted",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_registration_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил статус",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_requests",
                        to="accounts.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на регистрацию",
                "verbose_name_plural": "Заявки на регистрацию",
                "ordering": ("-created_at",),
            },
        ),
    ]
