# Generated by Django 5.2.4 on 2025-10-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_registrationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrequest",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_requests",
                to="accounts.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
