# Generated by Django 5.2.4 on 2025-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_registrationrequest_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина отказа"
            ),
        ),
    ]
