# Generated by Django 5.2.4 on 2025-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_registrationrequest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='can_save_project_applications',
            field=models.BooleanField(
                default=False, verbose_name='Может сохранять проектные заявки'
            ),
        ),
    ]
