# Generated by Django 5.2.4 on 2026-05-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=64, unique=True, verbose_name='Код'),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=128, unique=True, verbose_name='Код'),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, default='', max_length=512, verbose_name='Описание'
                    ),
                ),
                (
                    'value',
                    models.TextField(blank=True, default='', verbose_name='Значение'),
                ),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='semesters',
                to='accounts.academicyear',
                verbose_name='Учебный год',
            ),
        ),
    ]
