# Generated by Django 5.2.4 on 2026-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_semester_remove_is_active_code_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'submitted')),
                fields=('email',),
                name='unique_submitted_registration_email',
            ),
        ),
    ]
