# Generated by Django 5.2.4 on 2026-08-17 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_registrationrequest_email_partial_unique'),
        ('teams', '0008_studygroup_profile_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='teams.studygroup',
                verbose_name='Учебная группа',
            ),
        ),
        migrations.CreateModel(
            name='PreRegisteredStudent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, default='', max_length=150, verbose_name='Отчество'
                    ),
                ),
                (
                    'student_card',
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name='Студенческий билет',
                    ),
                ),
                (
                    'snils',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        max_length=11,
                        verbose_name='СНИЛС',
                    ),
                ),
                (
                    'personnel_number',
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name='Табельный номер (ID_E человека)',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pre_registered_students',
                        to='teams.studygroup',
                        verbose_name='Учебная группа',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='pre_registration',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Зарегистрированный пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Предрегистрация студента',
                'verbose_name_plural': 'Предрегистрации студентов',
                'ordering': ('last_name', 'first_name'),
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('snils', ''), _negated=True),
                        fields=('snils',),
                        name='unique_preregistered_student_snils',
                    )
                ],
            },
        ),
    ]
