# Generated by Django 5.2.4 on 2026-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_study_group_preregisteredstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='Учёная степень'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='Учёное звание'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='Должность'
            ),
        ),
    ]
