# Generated by Django 5.2.4 on 2026-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_mentor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredstudent',
            name='has_placeholder_user',
            field=models.BooleanField(
                default=False, verbose_name='Создан псевдо-аккаунт'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_placeholder',
            field=models.BooleanField(
                default=False, verbose_name='Псевдо-аккаунт контингента'
            ),
        ),
    ]
