# Generated by Django 5.2.4 on 2025-07-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Код статуса",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название статуса"
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Статус заявки",
                "verbose_name_plural": "Статусы заявок",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProjectApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("company", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="showcase.applicationstatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectApplicationStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Актор",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="showcase.projectapplication",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_status_logs",
                        to="showcase.applicationstatus",
                        verbose_name="Был статус",
                    ),
                ),
                (
                    "previous_status_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_logs",
                        to="showcase.projectapplicationstatuslog",
                        verbose_name="Предыдущий лог",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_status_logs",
                        to="showcase.applicationstatus",
                        verbose_name="Стало статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог изменения статуса заявки",
                "verbose_name_plural": "Логи изменения статусов заявок",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectApplicationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время комментария"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Поле, к которому относится комментарий",
                        max_length=100,
                        verbose_name="Поле",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "status_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="showcase.projectapplicationstatuslog",
                        verbose_name="Лог статуса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к изменению статуса заявки",
                "verbose_name_plural": "Комментарии к изменениям статусов заявок",
                "ordering": ["-created_at"],
            },
        ),
    ]
