# Generated by Django 5.2.4 on 2025-10-10 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Код института",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название института"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Позиция для сортировки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Институт",
                "verbose_name_plural": "Институты",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Код роли",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название роли"),
                ),
                (
                    "requires_department",
                    models.BooleanField(
                        default=False, verbose_name="Требует указания подразделения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="projectapplication",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "Проектная заявка",
                "verbose_name_plural": "Проектные заявки",
            },
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="additional_materials",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Дополнительные материалы"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="additional_materials_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/",
                verbose_name="Файл дополнительных материалов",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="barrier",
            field=models.TextField(default="", max_length=2000, verbose_name="Барьер"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="context",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Контекст"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="customer_contacts",
            field=models.TextField(
                default="",
                max_length=1000,
                verbose_name="Контактные данные представителя заказчика",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="customer_organization",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Наименование организации-заказчика",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="existing_solutions",
            field=models.TextField(
                default="", max_length=2000, verbose_name="Существующие решения"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="experts",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Эксперты"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="goal",
            field=models.TextField(default="", max_length=2000, verbose_name="Цель"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="needs_consultation",
            field=models.BooleanField(default=False, verbose_name="Нужна консультация"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="problem_holder",
            field=models.CharField(
                default="", max_length=255, verbose_name="Носитель проблемы"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="project_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("educational", "Учебный"),
                    ("educational_applied", "Учебно-прикладной"),
                    ("applied", "Прикладной"),
                ],
                max_length=50,
                null=True,
                verbose_name="Уровень проекта",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="project_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название проекта"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="recommended_tools",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Рекомендуемые инструменты"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="stakeholders",
            field=models.TextField(
                blank=True,
                max_length=2000,
                verbose_name="Другие заинтересованные стороны",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="user_department_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Подразделение (текст)"
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор заявки",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="company",
            field=models.CharField(max_length=255, verbose_name="Организация-заказчик"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="description",
            field=models.TextField(verbose_name="Описание проекта"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название проекта"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="target_institutes",
            field=models.ManyToManyField(
                blank=True,
                related_name="applications",
                to="showcase.institute",
                verbose_name="Целевые институты",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="showcase.userrole",
                verbose_name="Роль пользователя",
            ),
        ),
    ]
