# Generated by Django 5.2.4 on 2025-10-13 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "showcase",
            "0002_institute_userrole_alter_projectapplication_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email заявителя"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя заявителя"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия заявителя"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество заявителя"
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор заявки",
            ),
        ),
    ]
