# Generated by Django 5.2.4 on 2025-10-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0003_projectapplication_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="project_title",
        ),
    ]
