# Generated by Django 5.2.4 on 2025-10-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0004_remove_projectapplication_project_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="customer_organization",
        ),
    ]
