# Generated by Django 5.2.4 on 2025-10-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0005_remove_projectapplication_customer_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="customer_contacts",
        ),
    ]
