# Generated by Django 5.2.4 on 2025-10-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0006_remove_projectapplication_customer_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="user_role",
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="user_role_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Роль пользователя (текст)"
            ),
        ),
    ]
