# Generated by Django 5.2.4 on 2025-10-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0007_remove_projectapplication_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="additional_materials",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="additional_materials_file",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="barrier",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="context",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="email",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="existing_solutions",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="experts",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="needs_consultation",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="problem_holder",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="project_level",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="recommended_tools",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="stakeholders",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="target_institutes",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="user_department_text",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="user_role_text",
        ),
    ]
