# Generated by Django 5.2.4 on 2025-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0008_remove_projectapplication_additional_materials_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectapplication",
            name="description",
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="additional_materials",
            field=models.TextField(
                blank=True, null=True, verbose_name="Дополнительные материалы"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_division",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Подразделение автора",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Электронная почта автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_firstname",
            field=models.CharField(
                default="", max_length=100, verbose_name="Имя автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_middlename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_phone",
            field=models.CharField(
                default="", max_length=20, verbose_name="Телефон автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_role",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Роль автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="author_surname",
            field=models.CharField(
                default="", max_length=100, verbose_name="Фамилия автора"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="barrier",
            field=models.TextField(default="", verbose_name="Барьер"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="company_contacts",
            field=models.TextField(
                default="", verbose_name="Контактные данные представителя заказчика"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="context",
            field=models.TextField(blank=True, null=True, verbose_name="Контекст"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="existing_solutions",
            field=models.TextField(default="", verbose_name="Существующие решения"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="experts",
            field=models.TextField(blank=True, null=True, verbose_name="Эксперты"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="goal",
            field=models.TextField(default="", verbose_name="Цель"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="needs_consultation",
            field=models.BooleanField(default=False, verbose_name="Нужна консультация"),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="problem_holder",
            field=models.CharField(
                default="", max_length=255, verbose_name="Носитель проблемы"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="project_level",
            field=models.CharField(
                default="", max_length=100, verbose_name="Уровень проекта"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="recommended_tools",
            field=models.TextField(
                blank=True, null=True, verbose_name="Рекомендуемые инструменты"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="stakeholders",
            field=models.TextField(
                blank=True, null=True, verbose_name="Другие заинтересованные стороны"
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="target_institutes",
            field=models.ManyToManyField(
                blank=True,
                to="showcase.institute",
                verbose_name="Экспертам из какого института или академии стоит обратить особое внимание на заявку",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="company",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Наименование организации-заказчика",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название проекта"
            ),
        ),
    ]
