# Generated by Django 5.2.4 on 2025-10-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0009_remove_projectapplication_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectapplication",
            old_name="author_surname",
            new_name="author_lastname",
        ),
    ]
