# Generated by Django 5.2.4 on 2025-10-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0010_rename_author_surname_projectapplication_author_lastname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
