# Generated by Django 5.2.4 on 2025-10-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_registrationrequest_role"),
        ("showcase", "0011_delete_userrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplicationstatuslog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Изменение статуса"),
                    ("involved_user_added", "Добавлен причастный пользователь"),
                    ("involved_user_removed", "Удален причастный пользователь"),
                    ("involved_department_added", "Добавлено причастное подразделение"),
                    ("involved_department_removed", "Удалено причастное подразделение"),
                ],
                default="status_change",
                max_length=32,
                verbose_name="Тип действия",
            ),
        ),
        migrations.AddField(
            model_name="projectapplicationstatuslog",
            name="involved_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="involved_department_logs",
                to="accounts.department",
                verbose_name="Причастное подразделение",
            ),
        ),
        migrations.AddField(
            model_name="projectapplicationstatuslog",
            name="involved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="involved_user_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Причастный пользователь",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationInvolvedDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_involved_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved_departments",
                        to="showcase.projectapplication",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved_in_applications",
                        to="accounts.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Причастное подразделение",
                "verbose_name_plural": "Причастные подразделения",
                "ordering": ["-added_at"],
                "unique_together": {("application", "department")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationInvolvedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_involved_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved_users",
                        to="showcase.projectapplication",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved_in_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Причастный пользователь",
                "verbose_name_plural": "Причастные пользователи",
                "ordering": ["-added_at"],
                "unique_together": {("application", "user")},
            },
        ),
    ]
