# Generated by Django 5.2.4 on 2025-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0014_add_intermediate_approved_statuses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectapplicationcomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Комментарий к заявке",
                "verbose_name_plural": "Комментарии к заявкам",
            },
        ),
        migrations.AlterField(
            model_name="projectapplicationstatuslog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Изменение статуса"),
                    ("involved_user_added", "Добавлен причастный пользователь"),
                    ("involved_user_removed", "Удален причастный пользователь"),
                    ("involved_department_added", "Добавлено причастное подразделение"),
                    ("involved_department_removed", "Удалено причастное подразделение"),
                    ("application_updated", "Обновление заявки"),
                ],
                default="status_change",
                max_length=32,
                verbose_name="Тип действия",
            ),
        ),
    ]
