# Generated by Django 5.2.4 on 2025-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_alter_projectapplicationcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='application_year',
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name='Год заявки'
            ),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='print_number',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
                verbose_name='Номер для печати',
            ),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='year_sequence_number',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Номер заявки внутри года'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('application_year', 'year_sequence_number')},
        ),
    ]
