# Generated by Django 5.2.4 on 2025-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_projectapplication_application_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Название тега'
                    ),
                ),
                (
                    'category',
                    models.CharField(max_length=255, verbose_name='Категория тега'),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='tags',
            field=models.ManyToManyField(
                blank=True, to='showcase.tag', verbose_name='Теги'
            ),
        ),
    ]
