# Generated by Django 5.2.4 on 2025-12-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_projectapplication_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='is_internal_customer',
            field=models.BooleanField(
                default=False, verbose_name='Внутренний заказчик'
            ),
        ),
    ]
