# Generated by Django 5.2.4 on 2025-12-12 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_semester'),
        ('showcase', '0022_projectapplication_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPlan',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'plan',
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='План',
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='department_plans',
                        to='accounts.department',
                        verbose_name='Подразделение',
                    ),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='department_plans',
                        to='accounts.semester',
                        verbose_name='Семестр',
                    ),
                ),
            ],
            options={
                'verbose_name': 'План подразделения',
                'verbose_name_plural': 'Планы подразделений',
                'ordering': ['semester', 'department'],
                'unique_together': {('semester', 'department')},
            },
        ),
    ]
