# Generated by Django 5.2.4 on 2025-12-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_semester'),
        ('showcase', '0023_departmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tags',
                to='accounts.department',
                verbose_name='Подразделение',
            ),
        ),
    ]
