# Generated by Django 5.2.4 on 2025-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_semester'),
        ('showcase', '0024_add_department_to_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название тега'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'department')},
        ),
    ]
