# Generated by Django 5.2.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_semester"),
        ("showcase", "0029_projectapplication_img"),
        ("teams", "0005_studygroup_institute_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tracks",
                        to="accounts.semester",
                        verbose_name="Семестр",
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tracks",
                        to="teams.studygroup",
                        verbose_name="Учебная группа",
                    ),
                ),
                (
                    "project_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tracks",
                        to="showcase.projectapplication",
                        verbose_name="Проектная заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проектный трек",
                "verbose_name_plural": "Проектные треки",
                "ordering": ["semester", "study_group", "project_application"],
                "unique_together": {("semester", "study_group", "project_application")},
            },
        ),
    ]
