# Generated by Django 5.2.4 on 2026-08-17 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0031_refactor_projecttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='is_continuing',
            field=models.BooleanField(
                default=False, verbose_name='Продолжающийся проект'
            ),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='recommended_teams_count',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Рекомендуемое количество команд',
            ),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='track_composer_comment',
            field=models.TextField(
                blank=True, default='', verbose_name='Комментарий для составителя трека'
            ),
        ),
    ]
