# Generated by Django 5.2.4 on 2026-08-27 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0037_projecttrack_recommended_teams_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='max_team_members',
            field=models.PositiveIntegerField(
                default=7,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Максимальное количество человек в команде',
            ),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='min_team_members',
            field=models.PositiveIntegerField(
                default=4,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Минимальное количество человек в команде',
            ),
        ),
        migrations.AlterField(
            model_name='projecttrack',
            name='max_team_members',
            field=models.PositiveIntegerField(
                default=7,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Максимальное количество человек в команде',
            ),
        ),
        migrations.AlterField(
            model_name='projecttrack',
            name='min_team_members',
            field=models.PositiveIntegerField(
                default=4,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Минимальное количество человек в команде',
            ),
        ),
    ]
