# Generated by Django 5.2.4 on 2026-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0038_alter_team_member_limits_default_4_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='is_competitive_selection',
            field=models.BooleanField(default=False, verbose_name='Конкурсный отбор'),
        ),
    ]
