# Generated by Django 5.2.4 on 2026-09-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userwithemailprovision'),
        ('showcase', '0039_projectapplication_is_competitive_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSemesterSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'registration_opens_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Дата/время открытия записи на проект',
                    ),
                ),
                (
                    'closed_by_decision',
                    models.BooleanField(default=False, verbose_name='Закрыта решением'),
                ),
                (
                    'institute',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='semester_settings',
                        to='showcase.institute',
                        verbose_name='Институт',
                    ),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='institute_settings',
                        to='accounts.semester',
                        verbose_name='Семестр',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Настройки института в семестре',
                'verbose_name_plural': 'Настройки институтов в семестрах',
                'ordering': ['semester', 'institute'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('institute', 'semester'),
                        name='unique_institute_semester_settings',
                    )
                ],
            },
        ),
    ]
